env_default_config = {'n_rows': 50,
                      'n_cols': 50,
                      'sugar_growth_rate': 0.15,
                      'n_agents': 30,
                      'birth_endowment': 10,
                      'vision': 2,
                      'metabolism': 1,
                      'fertility_age': 5,
                      'infertility_age': 40,
                      'longevity': 50,
                      'max_iters': 500,
                      'max_capacity': 3,
                      'greedy_reward': False,
                      'update_stats': False
                      }
